; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
upload_port = COM3
monitor_speed = 115200
; extra_scripts = ./littlefsbuilder.py
build_flags = 
	-Os
	-ffunction-sections
	-fdata-sections
	-fno-stack-protector
	-fno-strict-aliasing
	-Wl,--gc-sections
	-Wl,--strip-all
	-Wl,--print-memory-usage
	-DCORE_DEBUG_LEVEL=0
	-DBOARD_HAS_PSRAM=0
	-DENV_API=\"e19f470114e4a4f4580249def7bd3643\"
	-DCONFIG_SPIRAM_DISABLE=1
	-DCONFIG_SPIRAM_SPIWIFI_INIT=0
	-DCONFIG_LWIP_IRAM_OPTIMIZATION=1
	-DCONFIG_NEWLIB_NANO_FORMAT=1
	-DCONFIG_WPA2_ENTP_AUTH_DISABLE=0
	-DCONFIG_TCP_WND_DEFAULT=5840
	-DCONFIG_TCP_RECVMBOX_SIZE=4
	-DCONFIG_UDP_RECVMBOX_SIZE=4
	-DCONFIG_TCPIP_TASK_STACK_SIZE=2048
lib_deps = 
	adafruit/RTClib @ ^2.1.4
	adafruit/Adafruit SSD1306 @ ^2.5.14
	adafruit/Adafruit MPU6050 @ ^2.2.6
	adafruit/Adafruit NeoPixel @ ^1.12.0
